### ISSUE TITLE
STUDIO: unrecognized configuration parameter "schema"

### ISSUE THREAD

**Issue by RSickenberg** [prisma/studio#1363]
### Bug description

Prisma Studio is crashing constantly but since it's a dev tool it's not critical.

### Severity

⚠️ Major: Breaks core functionality (e.g., migrations fail)

### Reproduction

Just bootstrap a docker project with latest postgress 16-alpine / studio with node 24.

### Expected vs. Actual Behavior

Expected: Working Studio
Actual:
```
select "ns"."nspname" as "schema", "cls"."relname" as "name", (select coalesce(json_agg(agg), '[]') from (select "att"."attname" as "name", "typ"."typname" as "datatype", "tns"."nspname" as "datatype_schema", "fk_ns"."nspname" as "fk_schema", "fk_cls"."relname" as "fk_table", "fk_att"."attname" as "fk_column", "pk_con"."conkey" is not null as "pk", "att"."attgenerated" != $1 as "computed", "att"."attnotnull" != $2 as "nullable", coalesce((select json_agg("enm"."enumlabel") as "o" from "pg_catalog"."pg_enum" as "enm" where "enm"."enumtypid" = "typ"."oid"), '[]') as "options" from "pg_catalog"."pg_attribute" as "att" inner join "pg_catalog"."pg_type" as "typ" on "typ"."oid" = "att"."atttypid" inner join "pg_catalog"."pg_namespace" as "tns" on "tns"."oid" = "typ"."typnamespace" left join "pg_catalog"."pg_constraint" as "pk_con" on "pk_con"."contype" = $3 and "pk_con"."conrelid" = "cls"."oid" and "att"."attnum" = any("pk_con"."conkey") left join "pg_catalog"."pg_constraint" as "fk_con" on "fk_con"."contype" = $4 and "fk_con"."conrelid" = "cls"."oid" and "att"."attnum" = any("fk_con"."conkey") left join "pg_catalog"."pg_class" as "fk_cls" on "fk_cls"."oid" = "fk_con"."confrelid" left join "pg_catalog"."pg_namespace" as "fk_ns" on "fk_ns"."oid" = "fk_cls"."relnamespace" left join "pg_catalog"."pg_attribute" as "fk_att" on "fk_att"."attrelid" = "fk_cls"."oid" and "fk_att"."attnum" = any("fk_con"."confkey") where "att"."attrelid" = "cls"."oid" and "att"."attnum" >= $5 and "att"."attisdropped" != $6) as agg) as "columns" from "pg_catalog"."pg_class" as "cls" inner join "pg_catalog"."pg_namespace" as "ns" on "cls"."relnamespace" = "ns"."oid" where "ns"."nspname" !~ $7 and "ns"."nspname" != $8 and "cls"."relkind" in ($9, $10)
```
```
unrecognized configuration parameter "schema"
```

### Frequency

Consistently reproducible

### Does this occur in development or production?

Only in development (e.g., CLI tools, migrations, Prisma Studio)

### Is this a regression?

Yes, it worked before V7.

### Workaround

Downgrade to latest v6.

### Prisma Schema & Queries

```prisma

generator client {
  provider               = "prisma-client"
  output                 = "../src/generated/prisma"
  generatedFileExtension = "ts"
  importFileExtension    = "ts"
  moduleFormat           = "esm"
  // runtime       = "vercel-edge"
}

datasource db {
  provider = "postgresql"
}

// Models are not shown for privacy reasons and is currently irrelevant.
```

### Prisma Config

```ts
import 'dotenv/config';
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
```

### Logs & Debug Info

```
// Debug logs here
```

<img width="2986" height="668" alt="Image" src="https://github.com/user-attachments/assets/9c126fe9-c948-47a1-bcea-f0e01721eeb5" />

### Environment & Setup

- **OS:** MacOS
- **Database:** Docker / Postgress
- **Node.js version:** 24

### Prisma Version

```
prisma               : 7.0.0
@prisma/client       : 7.0.0
Operating System     : darwin
Architecture         : arm64
Node.js              : v24.11.0
TypeScript           : 5.9.3
Query Compiler       : enabled
PSL                  : @prisma/prisma-schema-wasm 6.20.0-16.next-0c19ccc313cf9911a90d99d2ac2eb0280c76c513
Schema Engine        : schema-engine-cli 0c19ccc313cf9911a90d99d2ac2eb0280c76c513 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Default Engines Hash : 0c19ccc313cf9911a90d99d2ac2eb0280c76c513
Studio               : 0.8.0
```

**Comment by RSickenberg** [comment]
Found a workaround:
- Remove the `?schema=public` for the `--url` argument.

Probably related to:
- https://github.com/prisma/prisma/issues/28421 ?

**Comment by Tybot204** [comment]
Workaround works for me as well. Postgres defaults to using "public" if you don't provide a schema so this seems reasonable to use for the moment.

**Comment by igalklebanov** [comment]
Hey 👋 

Thanks for reporting this! 🙏

I have transferred this over to the `prisma/studio` repository where we track Studio issues.

**Comment by igalklebanov** [comment]
Regarding the "schema" query parameter. 

It is a non-standard made up parameter from Prisma ORM <=6. The error you're seeing comes from the database's validation.

New Studio is standalone. The URL you pass to it - via `prisma.config.ts` or `--url` is passed to the `postgres` package untouched - so it has to be a valid PostgreSQL URL with valid query parameters listed in https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS.

To change the default schema via the URL, you need to use [search_path](https://www.postgresql.org/docs/current/ddl-schemas.html#DDL-SCHEMAS-PATH) as follows: 

```url
postgresql://user:password@host:port/database?options=-c%20search_path%3Dmy_schema
```

**Comment by N0N4M3BNS** [comment]
On my side just happen samething like @RSickenberg . So my solution is 

Remove the `?schema=public` for the `--url` argument.

it will effect something problem if for production?

**Comment by rubelamin** [comment]
@RSickenberg 
Thanks for that. removing `?schema=public` from my .env DATABASE_URL also prisma studio works for me as well after upgrading to Prisma 7.0

**Comment by igalklebanov** [comment]
Should be resolved in `prisma@7.0.1`.

**Comment by kekubhai** [comment]
hey is this working file for everyonw I am still getting this error :

`select "ns"."nspname" as "schema", "cls"."relname" as "name", (select coalesce(json_agg(agg), '[]') from (select "att"."attname" as "name", "typ"."typname" as "datatype", "tns"."nspname" as "datatype_schema", "fk_ns"."nspname" as "fk_schema", "fk_cls"."relname" as "fk_table", "fk_att"."attname" as "fk_column", "pk_con"."conkey" is not null as "pk", "att"."attgenerated" != $1 as "computed", "att"."attnotnull" != $2 as "nullable", coalesce((select json_agg("enm"."enumlabel") as "o" from "pg_catalog"."pg_enum" as "enm" where "enm"."enumtypid" = "typ"."oid"), '[]') as "options" from "pg_catalog"."pg_attribute" as "att" inner join "pg_catalog"."pg_type" as "typ" on "typ"."oid" = "att"."atttypid" inner join "pg_catalog"."pg_namespace" as "tns" on "tns"."oid" = "typ"."typnamespace" left join "pg_catalog"."pg_constraint" as "pk_con" on "pk_con"."contype" = $3 and "pk_con"."conrelid" = "cls"."oid" and "att"."attnum" = any("pk_con"."conkey") left join "pg_catalog"."pg_constraint" as "fk_con" on "fk_con"."contype" = $4 and "fk_con"."conrelid" = "cls"."oid" and "att"."attnum" = any("fk_con"."conkey") left join "pg_catalog"."pg_class" as "fk_cls" on "fk_cls"."oid" = "fk_con"."confrelid" left join "pg_catalog"."pg_namespace" as "fk_ns" on "fk_ns"."oid" = "fk_cls"."relnamespace" left join "pg_catalog"."pg_attribute" as "fk_att" on "fk_att"."attrelid" = "fk_cls"."oid" and "fk_att"."attnum" = any("fk_con"."confkey") where "att"."attrelid" = "cls"."oid" and "att"."attnum" >= $5 and "att"."attisdropped" != $6) as agg) as "columns" from "pg_catalog"."pg_class" as "cls" inner join "pg_catalog"."pg_namespace" as "ns" on "cls"."relnamespace" = "ns"."oid" where "ns"."nspname" !~ $7 and "ns"."nspname" != $8 and "cls"."relkind" in ($9, $10)`
