### ISSUE TITLE
Fails to connect using "prisma+postgres:" connection strings.

### ISSUE THREAD

**Issue by igalklebanov** [prisma/studio#1409]
Hey 👋 

> I am facing an issue with prisma studio , it says introspection failed
> 
> ```write CONNECT_TIMEOUT accelerate.prisma-data.net:5432```
> 
> Can you help me out here ?
>  

 _Originally posted by @mohakchakraborty2004 in [#1408](https://github.com/prisma/studio/issues/1408#issuecomment-3583917411)_

`prisma+postgres:` connection strings are wrongly treated like regular `postgres:` connection strings.

**Comment by mohakchakraborty2004** [comment]
Hey there , so any updates or solution to this problem or why this is happening?

**Comment by mohakchakraborty2004** [comment]
Even on passing the prisma.config.ts file and the accelerate db url , directly from the terminal , it is still throwing introspection operation failed error. It is not able to detect or connect to the db , even ater explicitly passing it the URL through terminal itself with the ```--url``` tag

**Comment by igalklebanov** [comment]
Are you trying to connect to a Prisma Postgres instance?
Have you tried using the "direct TCP" connection string instead?

**Comment by mohakchakraborty2004** [comment]
I am not trying to connect to an instance , the command ```npx prisma studio``` is throwing this introspection error when the prisma db uses accelerate. If the db url is a normal postgress url it works just fine. 

How to do the "direct TCP" string method ? 

But anyway its still an issue right , that I am not able to access my accelerate prisma url using this command , but can do a normal postgres one.

**Comment by mohakchakraborty2004** [comment]
Oh okay , I just read the accelerate docs , in prisma 7 it does not allows to introspect an accelerate database. My bad @igalklebanov 

I will test again and let you know , and you can mark this issue off

**Comment by mohakchakraborty2004** [comment]
yes , I was right , accelerate URL cant be introspected in prisma studio in prisma 7. Problem is solved. Can close this issue.

**Comment by Tzadiko** [comment]
Hey, I just generated a new connection string, one that is **not** accelerate. It still fails for me the format is:

postgres://_alphanumeric string_:_secretkey_@db.prisma.io:_port_/postgres?sslmode=require_

Please help. Can you please provide documentation as to what the "Use the Direct TCP string connection method" is?

I went to console.prisma.io -> Select Database -> Dashboard -> Connect to Database -> Generate Connection and took the string that it provided in the format specified above.

Thanks

**Comment by Tzadiko** [comment]
Following up. Thanks
