### ISSUE TITLE
Copy & paste from a cell does not seem to work

### ISSUE THREAD

**Issue by madebysid** [prisma/studio#417]
Double click a cell > Cmd+A > Cmd+C should copy contents

Same for Cmd+X

**Comment by madebysid** [comment]
This was Firefox specific. 
(Actually it was Chrome specific, it was doing things it shouldn't be doing, and that masked my mistake)

Fixed now.

**Comment by brnyza** [comment]
For me, it's not working.
- Chrome v102.0.5005.63
- Prisma v3.14
- Windows 10

**Comment by seanlowe** [comment]
This is still broken. This seems like a pretty important functionality of a DB viewer.

Brave v1.64.116
Firefox 124.0.2 (64 bit)
Ubuntu 22.04
Prisma 5.11
