### ISSUE TITLE
Prisma Studio returns Malformed response for `count` query on Safari 14.0.3

### ISSUE THREAD

**Issue by Alex4386** [prisma/studio#658]
1. Prisma version (`prisma -v` or `npx prisma -v`):
```
prisma               : 2.21.0
@prisma/client       : 2.21.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/prisma/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : e421996c87d5f3c8f7eeadd502d4ad402c89464d
Studio               : 0.371.0
```

2. Logs from Developer Tools Console or Command line, if any:
<img width="779" alt="image" src="https://user-images.githubusercontent.com/27724108/114616945-74bcbc00-9ce2-11eb-941a-53508d66eadc.png">

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)
Yes, This Issue persists.

4. Prisma schema (if relevant):
[schema.prisma](https://github.com/meiling-gatekeeper/meiling/blob/main/prisma/schema.prisma)

**Extra explanation:**  
* I have tried to delete indexDB via running `window.indexedDB.deleteDatabase("Prisma Studio")`. It did not work.  
* I was only able to reproduce this issue on Safari. (version: 14.0.3)
* I was unable to reproduce this issue on Chrome. (version: 89.0.4389.114 (Official Build) (x86_64)) (i.e. Works fine on Chrome)
* This happened after I upgraded from prisma `2.19.0` to `2.21.0` (Edit: `2.21.2` is also affected.)
* deleting `node_modules` entirely and reinstalling dependencies again did not help.

**Comment by madebysid** [comment]
Hey @Alex4386, this issue looks like the same as #659, which was introduced with 2.21.0. Can you try the workaround I posted on that thread as well? If that works for you, then let's close this issue and keep everyone on #659 :)

**Comment by Alex4386** [comment]
> Hey @Alex4386, this issue looks like the same as #659, which was introduced with 2.21.0. Can you try the workaround I posted on that thread as well? If that works for you, then let's close this issue and keep everyone on #659 :)

Thanks!
But the proposed workaround (setting NODE_ENV to production does not seems to be working. ;( )

**Comment by Alex4386** [comment]
**Extra Information:**  
Although I am running on Safari, The machine that runs prisma studio is Ubuntu 20.04 LTS machine forwarded via SSH Tunneling. 

I think this issue (#658) is different from #659 since this issue have no relation to darwin query engine.

**Comment by madebysid** [comment]
Hmm weird. We just pushed out 2.21.1, can you update and try this again? Just making sure this wasn't already fixed!

**Comment by Alex4386** [comment]
Sorry about late reply, I will look for it ASAP.

**Comment by Alex4386** [comment]
![image](https://user-images.githubusercontent.com/27724108/115031757-7e713a00-9f03-11eb-9d70-1c90b8d1fd69.png)
**It seems it is not resolved for now.**

Let me try it again in incognito mode.

**Comment by madebysid** [comment]
Oh, this looks like the same issue as https://github.com/prisma/studio/issues/664, so you're not alone. I'll take a look at this!

**Comment by Alex4386** [comment]
> Oh, this looks like the same issue as #664, so you're not alone. I'll take a look at this!

Good, Is there anything I can help to troubleshoot the issue?

**Comment by madebysid** [comment]
@Alex4386 One thing you can do is try updating to the latest `dev` version of `prisma` as I suggested here: https://github.com/prisma/studio/issues/664#issuecomment-835362206

(Also hope you don't mind, going to close this issue in favor of https://github.com/prisma/studio/issues/664, so I don't have to keep track of two issues!)
