### ISSUE TITLE
fields with @updatedAt are not behaving as expected

### ISSUE THREAD

**Issue by chrisdrackett** [prisma/studio#728]
1. Prisma version (`prisma -v` or `npx prisma -v`): 2.26.0

When using prisma studio and adding records with a field that has `@updatedAt` I expect the item to be added with the current dateTime as the value for updated at. Instead it is getting the value `1970-01-01T00:00:00.000Z`

**Comment by chrisdrackett** [comment]
oh, this is probably worth trying!

**Comment by madebysid** [comment]
@chrisdrackett @sam3d That shouldn't be happening 🤔 

Without Studio, you shouldn't need to add an explicit `@default` value to `@updatedAt` fields. Prisma Client should automatically handle `@updatedAt` field values on its own. If this isn't happening for you, you should definitely create an issue on https://github.com/prisma/prisma!

In Studio too, this is unexpected. I'll take a look!

**Comment by chrisdrackett** [comment]
I figured this was a studio but because from what I can tell this works as expected in prisma itself!

**Comment by chrisdrackett** [comment]
for example this is what I see when I press the `Add Record` button in studio:

![https://cloud.drackett.com/8rnlRE/download](https://cloud.drackett.com/8rnlRE/download)

**Comment by madebysid** [comment]
Ah okay, yeah that's a bug in Studio. Will fix!

**Comment by madebysid** [comment]
This should be fixed in the latest `dev` version now (`npm i prisma@dev @prisma.client@dev`)! Fields that are marked as `@updatedAt` in your schema should now auto-populate with the current date & time. (If you already have a pending new record, you'll have to create a new one to observe this behaviour)

Do note that `dev` versions may contain unannounced breaking changes, so I wouldn't recommend using it in the long run for your app!
This will also make it to the next stable version of the Prisma CLI (Scheduled for July 27th). Let me know if this is still an issue!

**Comment by dashmug** [comment]
The variant of this bug still exists on Prisma 3.7.0.

When you click "Add Record", the updatedAt column is prepopulated by the time when you clicked that button.

![Screen Shot 2022-01-05 at 10 18 13 pm](https://user-images.githubusercontent.com/1972844/148209703-7990d4bf-24fe-4f22-85d2-c518e16b3de3.png)

As you edit the row and eventually save it, the row gets persisted in the DB but then the `createdAt` column (which is determined by the DB on write) will be later than the updatedAt.

![Screen Shot 2022-01-05 at 10 18 47 pm](https://user-images.githubusercontent.com/1972844/148209907-37603c8f-4410-48de-8285-25a745174cc5.png)
