### ISSUE TITLE
Unable to delete table rows with Byte ids

### ISSUE THREAD

**Issue by MarcGuiselin** [prisma/studio#804]
1. Prisma version (`prisma -v` or `npx prisma -v`):

````
prisma                  : 3.0.2
@prisma/client          : 3.0.2
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at ../../node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
````

2. Logs from Developer Tools Console or Command line, if any:
```
Type: undefined
Message: 
Invalid `prisma.session.delete()` invocation:

{
  where: {
    hashedToken: 'KORtDyuUQcz0VOEHga5DOQ=='
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~
  }
}

Argument hashedToken: Got invalid value 'KORtDyuUQcz0VOEHga5DOQ==' on prisma.deleteOneSession. Provided String, expected Bytes.



Code: undefined

Query:
prisma.session.delete(
{
  where: {
    hashedToken: "KORtDyuUQcz0VOEHga5DOQ==",
  },
}
)
```

3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

Yes

4. Prisma schema (if relevant):
```
datasource db {
  provider = "postgres"
  url      = env("DATABASE_URL")
}

model Session {
  hashedToken Bytes @id
}
```

**Comment by MarcGuiselin** [comment]
This issue occurs when manually trying to delete records in the prisma studio desktop app as show below. Prisma studio should use a buffer rather than a string to find and delete this row.
![image](https://user-images.githubusercontent.com/24906387/143180224-c14e3a78-8714-40b1-ae30-8aa5bdee6da4.png)
![image](https://user-images.githubusercontent.com/24906387/143180258-2cfec267-b53e-44a8-934e-801d18f03a5c.png)

**Comment by MarcGuiselin** [comment]
Issue persists with Prisma v3.6.0.

Example repo: https://github.com/MarcGuiselin/prisma-bug/

**Comment by madebysid** [comment]
Hey @MarcGuiselin, could you give 3.7.0 a shot as well? I haven't looked at your issue specifically, but there's been a fundamental change in how Studio makes its queries, and I think this may have been addressed. If not, let me know and I'll take a look. Thanks!

**Comment by MarcGuiselin** [comment]
Thanks Sid, unfortunately, it still throws the same error in 3.7.0

**Comment by MarcGuiselin** [comment]
@madebysid

**Comment by igalklebanov** [comment]
Hey :wave:

Prisma ORM 7 introduces a brand new standalone [Studio](https://www.prisma.io/docs/orm/tools/prisma-studio), built from the ground up to work everywhere, with or without Prisma ORM. Consequently, all "old Studio" issues are being closed as there won't be any further work on it. :mega:

The new Studio is also available in the Prisma VS Code extension and in the Prisma Console application. :electric_plug:

Help shape, improve and fix the new Studio with us in this repository by submitting bug reports and feature requests. :construction_worker:
