### ISSUE TITLE
isDirty Error on Studio

### ISSUE THREAD

**Issue by yovanoc** [prisma/studio#87]
![image](https://user-images.githubusercontent.com/7302317/64443705-d06c9f80-d0d2-11e9-836d-3b734a4c0056.png)

last alpha

**Comment by madebysid** [comment]
Hey @yovanoc, are you on alpha.165? This looks like an issue with Studio's IndexedDB data. I've been making some significant changes to it, and that is probably what broke this.

You should be able to fix this by deleting the `Prisma Studio` database from IndexedDB. Fortunately, I pushed out a new alpha release that handles IndexedDB migrations in a better way today, so you shouldn't have to (hopefully) do this again.

However, it'd be super helpful to take a look at an IndexedDB dump to figure out what's actually happening. Could you run the following code in Studio's DevTools Console?

```
(() => {
  const asyncForEach = (array, callback, done) => {
    const runAndWait = i => {
      if (i === array.length) done();
      return callback(array[i], () => runAndWait(i + 1));
    };
    return runAndWait(0);
  };

  const dump = {};
  const dbRequest = window.indexedDB.open("Test");
  dbRequest.onsuccess = () => {
    const db = dbRequest.result;
    const stores = Array.from(db.objectStoreNames);

    const tx = db.transaction(stores);
    asyncForEach(
      stores,
      (store, next) => {
        const req = tx.objectStore(store).getAll();
        req.onsuccess = () => {
          dump[store] = req.result;
          next();
        };
      },
      () => {
        console.log(JSON.stringify(dump));
      }
    );
  };
})();
```

All this does is log out all IDB data. There shouldn't be any real records here, just some metadata. If you could create a Gist with its output (it might be pretty huge), I'd really appreciate it, and it'll help me get to the root of the problem. Thanks!

**Comment by yovanoc** [comment]
Yeah, and same with alpha 166

![image](https://user-images.githubusercontent.com/7302317/64479447-7b568980-d1b7-11e9-968a-0e3187d2c4b9.png)

**Comment by madebysid** [comment]
Ah my bad, the database Name should be `Prisma Studio` (line 10). I've fixed the snippet in my comment on top as well.

**Comment by madebysid** [comment]
Once you get the dump, you should be able to delete the `Prisma Studio` database and get back to a working Studio

**Comment by yovanoc** [comment]
There is still an error 

![image](https://user-images.githubusercontent.com/7302317/64479537-e18fdc00-d1b8-11e9-8602-dfb8d42b469f.png)

But I have some data, here's the gist:

https://gist.github.com/yovanoc/21f0de1bd817212539524944fa62074b

**Comment by madebysid** [comment]
Perfect, the issue is that the active tab according to IndexedDB, is a tab that does not exist. I'll debug how this happened. Were you able to delete the DB and have the Studio work again?

**Comment by yovanoc** [comment]
Yes perfect

**Comment by madebysid** [comment]
Hey, I've been able to get to the bottom of this, the latest alpha (alpha.174 as of now) has a fix. It'll also land on the next preview this Thursday. Thanks for reporting!

Please reopen if you see this again.
